set.seed(1234)
tr <- trainControl(method="repeatedcv",repeats = 20, number=5)

daily.cog.qda <- train(class.cognitionImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,15)], method="qda")
print("qda done")
set.seed(1234)
daily.cog.tree <- train(class.cognitionImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,15)], method="rpart")
print("tree done")
set.seed(1234)
daily.cog.rf <- train(class.cognitionImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,15)], method="rf",ntree=10000)
print("random forest done")
set.seed(1234)
daily.cog.knn <- train(class.cognitionImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,15)], method="knn",tuneGrid=expand.grid(k=1:10))
print("knn done")