set.seed(1234)
tr <- trainControl(method="repeatedcv",repeats = 20, number=5)

timeofday.cvd.qda <- train(class.cvd ~ ., trControl = tr, data = time.of.day.df[,c(2:25,31)], method="qda")
print("cvd qda done")
set.seed(1234)
timeofday.cvd.tree <- train(class.cvd ~ ., trControl = tr, data = time.of.day.df[,c(2:25,31)], method="rpart")
print("cvd tree done")
set.seed(1234)
timeofday.cvd.rf <- train(class.cvd ~ ., trControl = tr, data = time.of.day.df[,c(2:25,31)], method="rf",ntree=10000)
print("cvd rf done")
set.seed(1234)
timeofday.cvd.knn <- train(class.cvd ~ ., trControl = tr, data = time.of.day.df[,c(2:25,31)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cvd knn done")

set.seed(1234)
timeofday.mob.qda <- train(class.mobilityImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,32)], method="qda")
print("mob qda done")
set.seed(1234)
timeofday.mob.tree <- train(class.mobilityImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,32)], method="rpart")
print("mob tree done")
set.seed(1234)
timeofday.mob.rf <- train(class.mobilityImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,32)], method="rf",ntree=10000)
print("mob rf done")
set.seed(1234)
timeofday.mob.knn <- train(class.mobilityImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,32)], method="knn",tuneGrid=expand.grid(k=1:10))
print("mob knn done")


set.seed(1234)
timeofday.cog.qda <- train(class.cognitionImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,33)], method="qda")
print("cog qda done")
set.seed(1234)
timeofday.cog.tree <- train(class.cognitionImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,33)], method="rpart")
print("cog tree done")
set.seed(1234)
timeofday.cog.rf <- train(class.cognitionImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,33)], method="rf",ntree=10000)
print("cog rf done")
set.seed(1234)
timeofday.cog.knn <- train(class.cognitionImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:25,33)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cog knn done")