set.seed(1234)
tr <- trainControl(method="repeatedcv",repeats = 20, number=5)

daily.mob.qda <- train(class.mobilityImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,14)], method="qda")
print("qda done")
set.seed(1234)
daily.mob.tree <- train(class.mobilityImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,14)], method="rpart")
print("tree done")
set.seed(1234)
daily.mob.rf <- train(class.mobilityImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,14)], method="rf",ntree=10000)
print("random forest done")
set.seed(1234)
daily.mob.knn <- train(class.mobilityImpaired ~ ., trControl = tr, data = daily.df[,c(2:7,14)], method="knn",tuneGrid=expand.grid(k=1:10))
print("knn done")