set.seed(1234)
tr <- trainControl(method="repeatedcv",repeats = 20, number=5)

#circadian.cvd.qda <- train(class.cvd ~ ., trControl = tr, data = circadian.df[,c(2:17,23)], method="qda")
#print("cvd qda done")
#set.seed(1234)
circadian.cvd.tree <- train(class.cvd ~ ., trControl = tr, data = circadian.df[,c(2:17,23)], method="rpart")
print("cvd tree done")
#set.seed(1234)
#circadian.cvd.rf <- train(class.cvd ~ ., trControl = tr, data = time.of.day.df[,c(2:17,23)], method="rf",ntree=10000)
#print("cvd rf done")
set.seed(1234)
circadian.cvd.knn <- train(class.cvd ~ ., trControl = tr, data = circadian.df[,c(2:17,23)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cvd knn done")

#set.seed(1234)
#circadian.mob.qda <- train(class.mobilityImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,24)], method="qda")
#print("mob qda done")
set.seed(1234)
circadian.mob.tree <- train(class.mobilityImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,24)], method="rpart")
print("mob tree done")
#set.seed(1234)
#circadian.mob.rf <- train(class.mobilityImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:17,24)], method="rf",ntree=10000)
#print("mob rf done")
set.seed(1234)
circadian.mob.knn <- train(class.mobilityImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,24)], method="knn",tuneGrid=expand.grid(k=1:10))
print("mob knn done")

#set.seed(1234)
#circadian.cog.qda <- train(class.cognitionImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,25)], method="qda")
#print("cog qda done")
set.seed(1234)
circadian.cog.tree <- train(class.cognitionImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,25)], method="rpart")
print("cog tree done")
#set.seed(1234)
#circadian.cog.rf <- train(class.cognitionImpaired ~ ., trControl = tr, data = time.of.day.df[,c(2:17,25)], method="rf",ntree=10000)
#print("cog rf done")
set.seed(1234)
circadian.cog.knn <- train(class.cognitionImpaired ~ ., trControl = tr, data = circadian.df[,c(2:17,25)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cog knn done")