set.seed(1234)
tr <- trainControl(method="repeatedcv",repeats = 20, number=5)

daily.lin.cvd.qda <- train(class.cvd ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,7)], method="qda")
print("cvd qda done")
set.seed(1234)
daily.lin.cvd.tree <- train(class.cvd ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,7)], method="rpart")
print("cvd tree done")
set.seed(1234)
daily.lin.cvd.rf <- train(class.cvd ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,7)], method="rf",ntree=10000)
print("cvd rf done")
set.seed(1234)
daily.lin.cvd.knn <- train(class.cvd ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,7)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cvd knn done")

set.seed(1234)
daily.lin.mob.qda <- train(class.mob ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,8)], method="qda")
print("mob qda done")
set.seed(1234)
daily.lin.mob.tree <- train(class.mob ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,8)], method="rpart")
print("mob tree done")
set.seed(1234)
daily.lin.mob.rf <- train(class.mob ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,8)], method="rf",ntree=10000)
print("mob rf done")
set.seed(1234)
daily.lin.mob.knn <- train(class.mob ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,8)], method="knn",tuneGrid=expand.grid(k=1:10))
print("mob knn done")


set.seed(1234)
daily.lin.cog.qda <- train(class.cog ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,9)], method="qda")
print("cog qda done")
set.seed(1234)
daily.lin.cog.tree <- train(class.cog ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,9)], method="rpart")
print("cog tree done")
set.seed(1234)
daily.lin.cog.rf <- train(class.cog ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,9)], method="rf",ntree=10000)
print("cog rf done")
set.seed(1234)
daily.lin.cog.knn <- train(class.cog ~ ., trControl = tr, data = daily.linearscaled.df[,c(1:6,9)], method="knn",tuneGrid=expand.grid(k=1:10))
print("cog knn done")
